theme: jekyll-theme-minimal
title: Dev Research
description: Road to Software Engineering Competence, A Zettelkasten
logo: https://res.cloudinary.com/twhiteblog/image/upload/v1594344481/dev-research-logo.png
show_downloads: false
highlighter: rouge
plugins:
  - jekyll-feed